# Hexo Theme Fluid
## Author: Fluid-dev
## Github: https://github.com/fluid-dev/hexo-theme-fluid
## Guide: https://hexo.fluid-dev.com/docs/guide/

## Global

# Site
favicon: /img/favicon.png
apple_touch_icon: /img/favicon-hires.png
tab_title_separator: ' - '
force_https: false

# Code
code:
  copy_btn: true
  language:
    enable: true
    default: text
  highlight:
    enable: true
    line_number: true
    lib: highlightjs
    highlightjs:
      style: github
      style_dark: github-dark-dimmed

# Some fun features
fun_features:
  # Typing animation for subtitle
  typing:
    enable: false

  # Anchor icon
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: left
    visible: hover
    icon:

  # Progress bar
  progressbar:
    enable: true
    color: '#2dd'
    options:
      showSpinner: false
      trickleSpeed: 100

# Dark mode
dark_mode:
  enable: true
  default: auto

# Color
color:
  body_bg_color: '#eee'
  body_bg_color_dark: '#182726'

  navbar_bg_color: '#2F544B'
  navbar_bg_color_dark: '#1F443C'

  navbar_text_color: '#fff'
  navbar_text_color_dark: '#d0d0d0'

  subtitle_color: '#fff'
  subtitle_color_dark: '#d0d0d0'

  text_color: '#3C5851'
  text_color_dark: '#C4C9C8'

  sec_text_color: '#71968C'
  sec_text_color_dark: '#A7ADAC'

  board_color: '#fff'
  board_color_dark: '#253833'

  post_text_color: '#2C5047'
  post_text_color_dark: '#C4C9C8'

  post_heading_color: '#1A2C2A'
  post_heading_color_dark: '#C4C9C8'

  post_link_color: '#03B7D6'
  post_link_color_dark: '#15D6E9'

  link_hover_color: '#30DE83'
  link_hover_color_dark: '#30DE83'

  link_hover_bg_color: '#F8FAF9'
  link_hover_bg_color_dark: '#36514A'

  line_color: '#EAEFEE'
  line_color_dark: '#43665D'

  scrollbar_color: '#C4C9C8'
  scrollbar_color_dark: '#68827B'
  scrollbar_hover_color: '#a6a6a6'
  scrollbar_hover_color_dark: '#9DB3AD'

  button_bg_color: transparent
  button_bg_color_dark: transparent
  button_hover_bg_color: '#F2F5F4'
  button_hover_bg_color_dark: '#467E71'

# Font
font:
  font_size: 16px
  font_family:
  letter_spacing: 0.02em
  code_font_size: 85%

# Custom file paths
custom_js:
custom_css:
  - //at.alicdn.com/t/c/font_4527289_ig13omtbhfp.css
  - /css/custom.css

# Analysis of website visitors
web_analytics:
  enable: false

# Canonical URL for Google Search
canonical:
  enable: false

# Lazy loading
lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

# Icon library
iconfont: //at.alicdn.com/t/c/font_1736178_k526ubmyhba.css

## Header

# Navigation bar
navbar:
  blog_title:
  ground_glass:
    enable: false
  menu:
    - key: home
      link: /
      icon: iconfont icon-home-fill
    - key: archive
      link: /archives/
      icon: iconfont icon-archive-fill
    # - key: category
    #   link: /categories/
    #   icon: iconfont icon-category-fill
    - key: tag
      link: /tags/
      icon: iconfont icon-tags-fill
    - key: about
      link: /about/
      icon: iconfont icon-user-fill
    - key: links
      link: /links/
      icon: iconfont icon-link-fill

# Search
search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  field: post
  content: true

# Banner
banner:
  parallax: true
  width_height_ratio: 1.0

# Arrows
scroll_down_arrow:
  enable: true
  banner_height_limit: 80
  scroll_after_turning_page: true
scroll_top_arrow:
  enable: true

# Open Graph metadata
open_graph:
  enable: true
  twitter_card: summary_large_image

## Footer

footer:
  content: |
    <i class="iconfont icon-copyright"></i>
    <span id="copyright_year">2021 - </span>
    <span>F_Qilin</span>
    <script>document.getElementById("copyright_year").innerText += new Date().getFullYear();</script>
    <br>
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
    <br>
    <!-- <a href="http://furgov.cn" rel="nofollow">兽ICP备202206210号</a> -->
  statistics:
    enable: false
  beian:
    enable: false

## Home Page

index:
  # Banner
  # NEW: This is the default image if switch_banner failed
  banner_img: /img/daily_pic/4.jpg
  banner_img_height: 100
  banner_mask_alpha: 0.5

  # Page subtitle
  slogan:
    enable: true
    text:
    api:
      enable: false

  # Post
  auto_excerpt:
    enable: true
  post_url_target: _self
  post_meta:
    date: true
    category: false  # true
    tag: true

  # Pin
  post_sticky:
    enable: true
    icon: iconfont icon-top

  # NEW: Check if URL matches the config
  check_url:
    enable: true
    note_type: warning
    # failed_text: '这个网站大概是镜像站。<br>主站链接：%s'
  
  # NEW: Use multiple images as banner
  switch_banner:
    # If true but no methods set, it will simply add scripts
    enable: true
    # RegExp list
    pattern:
      - 'img/daily_pic/*'
    # Perform a switch when refreshing
    # Available: *null* | random | time
    refresh: time
    # Minutes if "refresh" is set to "time"
    refresh_interval: 1440
    # Perform a switch when triggering selected event(s)
    # Available: click | dblclick | ...
    event:
      - dblclick
    # How to switch
    # Available: random | *forward* | backward
    method: forward

## Post Page

post:
  # Banner
  banner_img: /img/background.png
  banner_img_height: 70
  banner_mask_alpha: 0.5

  # Cover in home page
  default_index_img:

  # Meta
  meta:
    author:
      enable: false
    date:
      enable: true
      format: LL a
    wordcount:
      enable: true
    min2read:
      enable: true
      awl: 2  # Average word length
      wpm: 60  # Words per minute
    views:
      enable: false

  # Update date
  updated:
    enable: false
    # date_format: LL a
    # relative: false
    # note_class: info

  # Category
  category_bar:
    enable: false  # true
    # specific: false
    # placement: left
    # post_order_by: -date
    # post_limit: 0
  
  # Toc
  toc:
    enable: true
    placement: right
    headingSelector: h1,h2,h3,h4,h5,h6
    collapseDepth: 0

  # Copyright
  copyright:
    enable: true
    license: BY-SA
    license_encrypt: NORP
    author:
      enable: true
    post_date:
      enable: true
      format: LL
    update_date:
      enable: false
      # format: LL

  # Link to previous/next post
  prev_next:
    enable: true

  # Image
  image_caption:
    enable: true
  image_zoom:
    enable: true
    # img_url_replace: ['', '']
  
  # Footnote
  footnote:
    enable: true
    header: <h2 id="参考">参考</h2>

  # Math
  math:
    enable: true
    specific: true
    engine: mathjax

  # Flow chart
  mermaid:
    enable: true
    specific: true
    options:
      theme: default

  # Comment plugin
  comments:
    enable: true
    type: user

## Comment plugins

giscus:
  repo: FZQ0003/blog-source
  repo-id: R_kgDOL_Ip0Q
  category: Blog Comments
  category-id: DIC_kwDOL_Ip0c4Cftvq
  mapping: og:title
  reactions-enabled: 1
  emit-metadata: 0
  input-position: top
  lang: zh-CN

## Other Pages

# Archive
archive:
  banner_img: /img/background.png
  banner_img_height: 60
  banner_mask_alpha: 0.5

# Category
category:
  enable: false  # true
  # banner_img: /img/background.png
  # banner_img_height: 60
  # banner_mask_alpha: 0.5
  # order_by: name
  # collapse_depth: 0
  # post_order_by: -date
  # post_limit: 10

# Tags
tag:
  enable: true
  banner_img: /img/background.png
  banner_img_height: 80
  banner_mask_alpha: 0.5
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: '#BBBBEE'
    end_color: '#337ab7'

# About
about:
  enable: true
  banner_img: /img/background.png
  banner_img_height: 60
  banner_mask_alpha: 0.5
  avatar: /img/avatar.png
  name: F_Qilin
  intro: |
    Coding & Rendering | Blender | Python | Minecraft | ...
  icons:
    - class: iconfont icon-mail
      link: mailto:468403876@qq.com
      tip: E-Mail
    - class: iconfont icon-github-fill
      link: https://github.com/FZQ0003
      tip: GitHub
    - class: iconfont icon-bilibili
      link: https://space.bilibili.com/48122080
      tip: Bilibili
    - class: iconfont icon-twitter-x-line
      link: https://twitter.com/F_Qilin
      tip: X
    - class: iconfont icon-telegram
      link: https://t.me/F_Qilin
      tip: Telegram
    - class: iconfont icon-qq-fill
      qrcode: /img/qrcode/qm.qq.com_q_XuGnXogpqO.png
    - class: iconfont icon-juice
      qrcode: /img/qrcode/share.jagat.cn_u_eJ7uHHgZGU.png
    - class: iconfont icon-key
      link: /about/pubkey-fqilin-es.asc
      tip: GPG-Pubkey

# Custom
page:
  banner_img: /img/background.png
  banner_img_height: 60
  banner_mask_alpha: 0.5

# 404
page404:
  enable: true
  banner_img: /img/background.png
  banner_img_height: 85
  banner_mask_alpha: 0.5
  redirect_delay: 5000  # ms

# Links
links:
  enable: true
  banner_img: /img/background.png
  banner_img_height: 60
  banner_mask_alpha: 0.5
  items:
    - title: F_Qilin
      intro: 为什么要在这里放自己的？
      link: https://fqilin.top/
      avatar: https://avatars.githubusercontent.com/u/56470931
    - title: Billchenchina
      intro:
      link: https://billchen.bid/
      avatar: https://avatars.githubusercontent.com/u/7758042
    - title: pzm9012 | 铭渊
      intro:
      link: https://pzm9012.github.io/
      avatar: https://avatars.githubusercontent.com/u/73187647
    - title: YANFD
      intro:
      link: https://www.yanfd.online/
      avatar: https://www.yanfd.online/img/favicon.png
    - title: 熊谷 凌
      intro:
      link: https://furryr.github.io/
      avatar: https://avatars.githubusercontent.com/u/55276797
    - title: 阿方的博客
      intro: 现实的引力太过沉重，任何飞扬的思想都会砰然坠地。
      link: https://fang.blog.miri.site/
      avatar: https://img.lrurl.top/FangAvatar
    - title: SharpIce 锐冰
      intro: 世界很大，只是我的才华很有限，但我会继续学习的。
      link: https://sharpice.top/
      avatar: https://sharpice.top/favicon.png
    - title: VArcade
      intro: 做四四方方的动画
      link: https://space.bilibili.com/269076545
      avatar:
    - title: Varcade-BL Rig
      intro: 不再更新的MC人模
      link: https://varcade-bl.readthedocs.io/
      avatar:
  onerror_avatar:
  custom:
    enable: true
    content: |
      <hr>
      <p>在下方留言申请加入我的友链，按如下格式提供信息：</p>
      <ul>
        <li>博客名：F_Qilin的小窝</li>
        <li>简介：一个小小的个人博客</li>
        <li>链接：https://blog.fqilin.top/</li>
        <li>图片：https://blog.fqilin.top/img/avatar.png</li>
      </ul>
  comments:
    enable: true
    type: user

## Static Assets

static_prefix:
  # Internal
  internal_js: /js
  internal_css: /css
  internal_img: /img

  anchor: https://lib.baomitu.com/anchor-js/5.0.0/
  github_markdown: https://lib.baomitu.com/github-markdown-css/4.0.0/
  jquery: https://lib.baomitu.com/jquery/3.6.4/
  bootstrap: https://lib.baomitu.com/twitter-bootstrap/4.6.1/
  tocbot: https://lib.baomitu.com/tocbot/4.20.1/
  typed: https://lib.baomitu.com/typed.js/2.0.12/
  fancybox: https://lib.baomitu.com/fancybox/3.5.7/
  nprogress: https://lib.baomitu.com/nprogress/0.2.0/
  mathjax: https://lib.baomitu.com/mathjax/3.2.2/
  clipboard: https://lib.baomitu.com/clipboard.js/2.0.11/
  mermaid: https://lib.baomitu.com/mermaid/8.14.0/
  gitalk: https://lib.baomitu.com/gitalk/1.8.0/
  hint: https://lib.baomitu.com/hint.css/2.7.0/
  moment: https://lib.baomitu.com/moment.js/2.29.4/
