# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: F_Qilin的小窝
subtitle: 一个小小的个人博客
description:
keywords:
author: F_Qilin
language: zh-CN
timezone: Asia/Harbin

# URL
url: https://blog.fqilin.top
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  # - html/**

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter:  # Use highlighter from theme

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: 未分类
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
  - "img/archive/*"
  - "img/daily_pic.png"
  - "img/logo-head-2023.png"  # TODO
  - "**/test*"
  - "**/*.py"
ignore:
  # Remove theme files
  - "**/img/police_beian.png"
  - "**/img/fluid.png"
  - "**/img/default.png"
  - "**/js/leancloud.js"

# Extensions
theme: fluid

# hexo-renderer-marked
# marked:
#   prependRoot: true
#   postAsset: true

# hexo-renderer-markdown-it
markdown:
  plugins:
    # - markdown-it-footnote
    - markdown-it-ins
  anchors:
    collisionSuffix: '-'
    permalink: false  # true
    permalinkSide: 'right'
  images:
    lazyload: true
    # prepend_root: true
    # post_asset: true

# hexo-renderer-stylus
stylus:
  compress: true
  sourcemaps:
    comment: false
    inline: false
    sourceRoot: ''
    basePath: .
  plugins:  # 'nib'

# hexo-blog-encrypt
encrypt:
  abstract: '[该文章已被加密]'
  message: 请输入密码查看该文章
  # tags: secrets.ENCRYPT_TAGS_LIST
  theme: shrink
  wrong_pass_message: 密码错误，请重新输入。
  wrong_hash_message: 文章校验失败，不过还是能看看解密后的内容。
  silent: true

# minify-html
minify_html:
  enable: true
  priority: 999
  config:
    do_not_minify_doctype: true
    ensure_spec_compliant_unquoted_attribute_values: true
    keep_closing_tags: true
    # keep_html_and_head_opening_tags: false
    # keep_spaces_between_attributes: false
    keep_comments: true
    # keep_ssi_comments: false
    # preserve_brace_template_syntax: false
    # preserve_chevron_percent_template_syntax: false
    minify_js: true
    minify_css: true
    # remove_bangs: false
    # remove_processing_instructions: false

# minify-js
# minify_js:
#   enable: true
#   priority: 999

# lightningcss
# lightningcss:
#   enable: true
#   priority: 999

# Deployment
deploy:
  type: ''

# Custom or auto-generated configs
